### ISSUE TITLE
JOSM - Openstreetcam Plugin...

### ISSUE THREAD

**Issue by jbowkett84** [openstreetcam/openstreetview.org#121]
Are there any instructions on how to use this plugin? I have installed the plugin and opened it but no matter what I do I have a blank screen next to my map in JOSM?!

**Comment by beataj-telenav** [comment]
You can find more information about the plugin at: http://blog.improve-osm.org/en/2017/02/openstreetcam-josm-plugin/. In order to use the plugin you need to open manually the OpenStreetCam layer and OpenStreetCam panel. The plugin displays data starting with zoom level 11, individual image locations should show up starting with zoom level 18. In order to visualize images, you need to select image locations from the map first.
Any other plugin related questions/issues please post to: https://github.com/openstreetcam/josm-plugin.
