### ISSUE TITLE
Can't open tracks from user page in new tab

### ISSUE THREAD

**Issue by ToeBee** [openstreetcam/openstreetview.org#144]
Whatever you are doing to open tracks when you click on them in the user profile is interfering with the ability to open a new tab with that track in it. I suspect it is being done with a javascript onclick event and the browser doesn't see them as actual links. I would like to be able to open several tracks at once to review some things on them without having to exit back out to my user profile every time.

At the end of the day, I would like for CTRL-click and middle mouse click to work as expected and open the given track in a new tab.

**Comment by alexandrui-telenav** [comment]
It's indeed a problem, it annoyed me as well for a while. To give a bit of context, the website is built on a bit of a shaky foundation, and unfortunately comes with some undesired glitches such as this one.. We started from scratch now and have a 2.0 implementation which will be in production very soon ( it's on http://oscfront.beta.openstreetcam.org currently ). This problem is fixed there, sorry about this..
