### ISSUE TITLE
Thumbnails not correctly aligned for all window sizes

### ISSUE THREAD

**Issue by ralucac-telenav** [openstreetcam/openstreetview.org#15]
![list](https://cloud.githubusercontent.com/assets/15245281/17173478/c33a65b2-5403-11e6-8143-a4ec2ea271fb.png)

**Comment by james2432** [comment]
The problem is that you put every 6 items in a "row" class div. All items should be put in the same "row" as the row class in bootstrap adds a css clear, thus creating the gap you see.

If you put everything in the same "row" div instead of splitting them, everything will be floated left and will scale properly

**Comment by martijnv-telenav** [comment]
@alexandrui-telenav did we fix this already?

**Comment by james2432** [comment]
still exists
![stillexists](https://cloud.githubusercontent.com/assets/498547/17573666/ea2c59d8-5f29-11e6-8ef4-cca35a00e90b.PNG)

**Comment by james2432** [comment]
this is fixed now.
