### ISSUE TITLE
Does OSV record rotation of the photos?

### ISSUE THREAD

**Issue by alex9099** [openstreetcam/openstreetview.org#161]
Does OSV Record rotation of the photo (and GPS altitude)?

If not this seems to me necessary for in the later process stich the photos into one globe, like Google's street view

For example, I was in a bus trip and wanted to contribute, but I could only took to the right side of the road

Edit: another non related question, are the photos reviewed before publishing? (Like to blue faces and etc) in Portugal it is ilegal to take photos of people without their written consent

**Comment by bogdans-telenav** [comment]
@alex9099 
1. If you are referring to heading when asking of rotation and the answer is yes we are saving the heading. We are also saving GPS altitude (and its reported error witch is in the range of 10 meters) if you are trying to get the sense of relative altitude from the start of the trip you could use the pressure readings.  here you can find a long discussion about all the recorded sensors. https://github.com/openstreetcam/openstreetview.org/issues/109
2. OSC is processing all uploaded photos in order to automatically blur faces and license plates. And will not display or grant public access to unprocessed photos. (only the user that uploaded a photo is able to see a unprocessed photo)
I will now close this issue. If you believe that you need further explanation reading any other sensor please create a new issue.

**Comment by alex9099** [comment]
ok thanks ;)
