### ISSUE TITLE
stuck in processing & website delays

### ISSUE THREAD

**Issue by minty** [openstreetcam/openstreetview.org#98]
Hi,

re: http://openstreetcam.org/user/minty

I've got 4 tracks from September 2016 that are still showing as "Processing"

And in the last 48 hours uploaded ~8GB of tracks, some of which are showing up on my profile, most of which aren't a few hours after the app finished uploading them.

(a) is there any way I can get the un-processed tracks from many months ago to complete?

(b) I understand here might be processing delays in updating the website, but it would be good if we could get a guide / status page, because right now it just looks like the site is broken and/or lost my uploads.

I've asked on twitter a couple times, but gotten zero response.

How do I productively help here?

**Comment by james2432** [comment]
I also have one stuck in processing:
http://beta.openstreetcam.org/details/11618/1

**Comment by martijnv-telenav** [comment]
This should be fixed now -- sorry about this! We try to watch Twitter more closely, sorry if you didn't get a response there. 

Closing but feel free to re-open if it isn't fixed for you.

**Comment by minty** [comment]
Is there likely to be a delay for the fix to appear?  I still have the 4 "processing" tracks from Sept 2016, eg http://openstreetcam.org/details/21404/0

<img width="955" alt="screen shot 2017-01-25 at 23 53 57" src="https://cloud.githubusercontent.com/assets/89659/22314478/990b48de-e359-11e6-8b61-d63874f834c5.png">

Also, of the 9 tracks and ~8GB I finished uploading by 9am GMT on 24th Jan 2017, 2 are shown as done, 3 are still flagged as "Processing" and 4 are totally missing from my (logged in) profile page

eg http://openstreetcam.org/details/31598/0

<img width="945" alt="screen shot 2017-01-25 at 23 56 37" src="https://cloud.githubusercontent.com/assets/89659/22314536/fba9cd6c-e359-11e6-8e1a-5ebfda520471.png">

**Comment by james2432** [comment]
http://beta.openstreetcam.org/details/11618/1
Still trying to be processed.

**Comment by james2432** [comment]
@minty 
The tracks with no KM's on them is most likely because the server never receiving the "this track is complete" message. 

1. If you are uploading images via the python scripts what you can do is create an empty folder.
2. Create a txt file named "sequence_file.txt"
3. Create a txt file named "count_file.txt"
4. Put the number 1 in count_file.txt and save.
5. In sequence_file.txt put the number of the sequence (i.e. http://openstreetcam.org/details/31598/0 would be 31598)
6. Point the scripts to "upload" the empty folder(no images, just text files), this will detect there are no more images to upload and send the "done" message to the server to begin processing.

@martijnv-telenav Can you re-open this issue as there are still tracks waiting to be processed.

**Comment by minty** [comment]
@james2432 thanks for that - I've never used the python scripts, but I'll give them a go.  Sounds like a super little hack :)

It might take me a few days to get around to it tho.

One other problem I have : When I started uploading from last weekends trip, the iOS app said I had 9 tracks.  There are 5 showing on my website profile, and 4 are MIA.

So I don't even have a sequence number for those 4 that are MIA ... they've just vanished into the ether :(

**Comment by james2432** [comment]
created #100 as this one is closed...
